export const salaryCalculatorStrings = {
  title: "Egypt Salary Calculator",
  description:
    "Calculate take-home pay for Egyptian residents with progressive tax brackets and social insurance deductions",
  calculationParameters: "Calculation Parameters",
  calculationMode: "Calculation Mode",
  grossToNet: "Gross → Net",
  netToGross: "Net → Gross",
  monthlyGrossSalary: "Monthly Gross Salary",
  targetMonthlyNetSalary: "Target Monthly Net Salary",
  enterAmount: "Enter amount",
  currency: "Currency",
  egp: "EGP",
  usd: "USD",
  exchangeRate: "USD to EGP Exchange Rate",
  refresh: "Refresh",
  fetchingRate: "Fetching live rate...",
  liveRateFetched: "Live rate fetched:",
  usingFallbackRate: "Using fallback rate:",
  clickRefresh: "Click refresh to get the latest rate",
  calculate: "Calculate",
  results: "Results",
  monthlyBreakdown: "Monthly Breakdown",
  grossSalary: "Gross Salary:",
  employeeSi: "Employee SI:",
  incomeTax: "Income Tax:",
  takeHomePay: "Take Home Pay:",
  annualSummary: "Annual Summary",
  taxableIncome: "Taxable Income:",
  enterDetails: "Enter your details and click \"Calculate\" to see results",
  aboutCalculator: "About This Calculator",
  basedOn2026: "Based on 2026 Egyptian tax brackets and social insurance rates",
  supportsCurrency: "Supports both EGP and USD calculations with customizable exchange rates",
  includesAllowance: "Includes personal allowance deduction for residents (EGP 20,000 annually)",
  siCalculation: "Social insurance is calculated on gross salary with minimum and maximum caps",
  invalidAmount: "Please enter a valid amount",
  salaryPeriod: "Salary Period",
  monthly: "Monthly",
  annual: "Annual",
  annualGrossSalary: "Annual Gross Salary",
  targetAnnualNetSalary: "Target Annual Net Salary",
} as const;

export type SalaryCalculatorStrings = typeof salaryCalculatorStrings;

